-- ========================================================
-- SUPABASE DATABASE SETUP FOR TECHWORLD CMS
-- Hướng dẫn: Copy toàn bộ nội dung này dán vào SQL Editor của Supabase và nhấn RUN.
-- ========================================================

-- 1. Tạo bảng Bài viết (Posts)
CREATE TABLE IF NOT EXISTS posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  category TEXT,
  excerpt TEXT,
  content TEXT,
  image_key TEXT,
  published BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tạo bảng Bình luận (Comments)
CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT REFERENCES posts(id) ON DELETE CASCADE,
  user_name TEXT NOT NULL,
  comment_body TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS site_content (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  value TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Tạo bảng Tin nhắn liên hệ (Contact Messages)
CREATE TABLE IF NOT EXISTS contact_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT,
  email TEXT,
  phone TEXT,
  service TEXT,
  message TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Tắt bảo mật RLS để có thể thao tác trực tiếp từ Frontend
ALTER TABLE posts DISABLE ROW LEVEL SECURITY;
ALTER TABLE comments DISABLE ROW LEVEL SECURITY;
ALTER TABLE site_content DISABLE ROW LEVEL SECURITY;
ALTER TABLE contact_messages DISABLE ROW LEVEL SECURITY;

-- 5. Chèn dữ liệu mẫu cho Site Content (Nếu chưa có)
INSERT INTO site_content (key, value)
VALUES 
  ('hero_badge', 'Latest Tech News · AI · Programming · Cybersecurity'),
  ('hero_title', 'Explore the Future of Technology'),
  ('hero_desc', 'Latest news about AI, programming, cybersecurity, and modern technology trends.'),
  ('contact_phone', '+1 800 555 0199'),
  ('contact_email', 'hello@TechWorld.com'),
  ('contact_address', '42 Harbor View, San Francisco, CA')
ON CONFLICT (key) DO NOTHING;

-- 6. Tạo Bucket cho ảnh (Tạo tự động)
INSERT INTO storage.buckets (id, name, public)
VALUES ('blog-images', 'blog-images', true)
ON CONFLICT (id) DO NOTHING;

-- Lệnh này sẽ tắt hàng rào bảo mật để bạn có thể lưu bài thoải mái
ALTER TABLE posts DISABLE ROW LEVEL SECURITY;



-- 1. Cho phép mọi người xem ảnh (SELECT)
CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING (bucket_id = 'blog-images');

-- 2. Cho phép mọi người tải ảnh lên (INSERT)
CREATE POLICY "Public Upload" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'blog-images');

-- 3. Cho phép cập nhật và xóa (Nếu cần)
CREATE POLICY "Public Update" ON storage.objects FOR UPDATE USING (bucket_id = 'blog-images');
CREATE POLICY "Public Delete" ON storage.objects FOR DELETE USING (bucket_id = 'blog-images');

-- Tắt hoàn toàn RLS cho bảng comments (giống như trong file setup của mình)
ALTER TABLE comments DISABLE ROW LEVEL SECURITY;

-- Tắt RLS cho bảng nội dung tĩnh
ALTER TABLE site_content DISABLE ROW LEVEL SECURITY;

ALTER TABLE posts ADD COLUMN tags TEXT;


-- 1. Kích hoạt Realtime cho bảng tin nhắn
ALTER TABLE contact_messages REPLICA IDENTITY FULL;
ALTER publication supabase_realtime ADD TABLE contact_messages;

-- 2. Kích hoạt Realtime cho bảng bình luận
ALTER TABLE comments REPLICA IDENTITY FULL;
ALTER publication supabase_realtime ADD TABLE comments;

-- 3. (Quan trọng) Cho phép anonymous (khách) có thể lắng nghe Realtime
-- Lưu ý: Nếu lệnh này báo lỗi thì có nghĩa là bảng của bạn đã được cấu hình đúng rồi
GRANT USAGE ON SCHEMA public TO anon;
GRANT SELECT ON contact_messages TO anon;
GRANT SELECT ON comments TO anon;
